apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader
subjects:
- kind: User
  name: user-one
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
