apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator
subjects:
- kind: User
  name: user-second
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: operator
  apiGroup: rbac.authorization.k8s.io
